package jp.evo.btm.fragment;

public enum FragmentType {

	DEPARMENT, ADD_DEPARMENT, SUB_DEPARMENT, ADD_SUB_DEPARTMENT, USER, ADD_USER, USER_DETAIL, USER_CHANGE_PASSWORD, TRAVEL, TRAVEL_DETAIL, SEARCH_USER, TRAVEL_REGISTER, TRAVEL_LIST, TRAVEL_FILTER, WEBVIEW;
}
